# Generated by Django 4.2.1 on 2024-03-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('postdate', models.DateField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
