# Generated by Django 4.2.1 on 2024-03-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_s_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_achievement',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
