# Generated by Django 4.2.1 on 2024-03-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_alter_s_achievement_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_achievement',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
