# Generated by Django 4.2.1 on 2024-04-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_s_achievement_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='en_word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=4)),
            ],
        ),
    ]
